# Generated by Django 5.1.5 on 2025-02-18 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('statsID', models.AutoField(primary_key=True, serialize=False)),
                ('yourPoints', models.IntegerField(default=0)),
                ('co2Saved', models.IntegerField(default=0)),
                ('plasticSaved', models.IntegerField(default=0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
