# Generated by Django 5.1.6 on 2025-03-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='co2Saved',
            new_name='metalRecycled',
        ),
        migrations.RenameField(
            model_name='stats',
            old_name='plasticSaved',
            new_name='packagingRecycled',
        ),
        migrations.AddField(
            model_name='stats',
            name='paperRecycled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='plasticRecycled',
            field=models.IntegerField(default=0),
        ),
    ]
