# Generated by Django 5.1.5 on 2025-03-18 21:54

from django.db import migrations, models

def set_initial_total_points(apps, schema_editor):
    Stats = apps.get_model('stats', 'Stats')
    for stats in Stats.objects.all():
        stats.yourTotalPoints = stats.yourPoints
        stats.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_initial_total_points),
    ]
