# Generated by Django 5.1.5 on 2025-03-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_stats_yourtotalpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='yourTotalPoints',
            field=models.IntegerField(default=0),
        ),
    ]
