# Generated by Django 5.1.5 on 2025-03-20 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_rename_co2saved_stats_metalrecycled_and_more'),
        ('stats', '0003_stats_yourtotalpoints'),
    ]

    operations = [
    ]
