# Generated by Django 5.1.5 on 2025-03-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_merge_20250320_2335'),
        ('stats', '0004_merge_20250320_2341'),
    ]

    operations = [
    ]
