# Generated by Django 5.1.6 on 2025-03-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLocation',
            fields=[
                ('locationID', models.AutoField(primary_key=True, serialize=False)),
                ('locationName', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('quizID', models.IntegerField()),
            ],
        ),
    ]
