# Generated by Django 5.1.5 on 2025-03-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gamekeeper', 'Gamekeeper'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
