services:


  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=sustainabilityapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webnet  # Ensure communication with the web service


  web:
    build: .
    container_name: django_app
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ENV=production
      - POSTGRES_DB=sustainabilityapp
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./apps:/app/apps

    ports:
      - "8000:8000"
    networks:
      - webnet  # Ensure communication with nginx
    depends_on:
      - db # Ensure the database is running before starting the web service

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro  # Mount SSL certificates from host
      - /etc/ssl/private:/etc/ssl/private:ro  # Mount private key from host
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - webnet  # Ensure communication with the web service

networks:
  webnet:  # Define a custom network for web and nginx to communicate
    driver: bridge

volumes:
    postgres_data:
      driver: local