version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    command: gunicorn --bind 0.0.0.0:8000 SustainabilityApp.wsgi:application  # Gunicorn command
    volumes:
      - .:/app
    ports:
      - "8000:8000"



  nginx:
      image: nginx:latest
      container_name: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./static:/app/static  # Static files
        - ./media:/app/media  # Media files
      ports:
        - "80:80"
      depends_on:
        - web