services:
  web:
    build: .
    container_name: django_app
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    #command: "gunicorn --bind 0.0.0.0:8000 SustainabilityApp.wsgi:application"


    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./SustainabilityApp:/app/SustainabilityApp

    ports:
      - "8000:8000"
    networks:
      - webnet  # Ensure communication with nginx

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - webnet  # Ensure communication with the web service

networks:
  webnet:  # Define a custom network for web and nginx to communicate
    driver: bridge