# Generated by Django 5.1.5 on 2025-02-18 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('quizID', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=512)),
                ('answer', models.CharField(max_length=512)),
                ('other1', models.CharField(max_length=512)),
                ('other2', models.CharField(max_length=512)),
                ('other3', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='quizTimeout',
            fields=[
                ('timeoutID', models.AutoField(primary_key=True, serialize=False)),
                ('timeout', models.DateTimeField()),
                ('quizID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
