# Generated by Django 5.1.5 on 2025-03-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='landmark_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
