# Generated by Django 5.1.5 on 2025-02-23 16:13
import csv
from pathlib import Path

from django.db import migrations


def load_initial_quizzes(apps, schema_editor):
    ModelName = apps.get_model('quiz', 'quiz')
    csv_file = Path(__file__).parent / 'sustainabilityQuestions.csv'

    with open(csv_file, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            ModelName.objects.get_or_create(**row)  # Ensures no duplicates

class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_quizzes),
    ]
