# Generated by Django 5.1.5 on 2025-03-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='locationID',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
