# Generated by Django 5.1.5 on 2025-03-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_landmark_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='landmark_id',
        ),
        migrations.AddField(
            model_name='quiz',
            name='locationID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
