# Generated by Django 5.1.5 on 2025-03-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='locationID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
