# Generated by Django 5.1.5 on 2025-03-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('binID', models.AutoField(primary_key=True, serialize=False)),
                ('binIdentifier', models.CharField(default='No identifier', max_length=50)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
    ]
