# Generated by Django 5.1.5 on 2025-02-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=512)),
                ('itemDescription', models.CharField(max_length=512)),
                ('itemCarbonValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QRCodes',
            fields=[
                ('qrID', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=512)),
                ('qrCodeLink', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('binID', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=512)),
                ('qrCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recycling.qrcodes')),
            ],
        ),
    ]
