# Generated by Django 5.1.6 on 2025-03-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.AlterField(
            model_name='bin',
            name='qrCode',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='QRCodes',
        ),
    ]
