# Generated by Django 5.1.5 on 2025-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0003_remove_bin_location_bin_latitude_bin_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='binIdentifier',
            field=models.CharField(default='No identifier', max_length=50),
        ),
    ]
