# Generated by Django 5.1.5 on 2025-03-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0003_remove_bin_location_bin_latitude_bin_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='qrCode',
        ),
    ]
