# Generated by Django 5.1.5 on 2025-03-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0004_bin_binidentifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='qrCode',
        ),
    ]
