# Generated by Django 5.1.5 on 2025-03-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0004_remove_bin_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='binIdentifier',
            field=models.CharField(default='No identifier', max_length=50),
        ),
    ]
