# Generated by Django 5.1.5 on 2025-02-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_block_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Garden',
        ),
    ]
