# Generated by Django 5.1.5 on 2025-03-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_remove_garden_filepath_garden_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='blockPath',
            field=models.FileField(blank=True, null=True, upload_to='blocks/'),
        ),
    ]
