# Generated by Django 5.1.5 on 2025-03-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_block_blockpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='visibleName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
